DROP TABLE name;

ALTER TABLE person ADD firstName VARCHAR(100) NOT NULL, ADD middleName VARCHAR(100) NOT NULL, ADD lastName VARCHAR(100) NOT NULL, ADD suffix VARCHAR(100) NOT NULL, ADD title VARCHAR(100) NOT NULL;


